name: Lint Code

on:
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install Linter
        run: go install golang.org/x/lint/golint

      - name: Lint the project
        run: |
          output=$(golint ./...)
          if [ -n "$output" ]; then
            echo "$output"
            echo "golint found issues. Please fix them before merging."
            exit 1
          else
            echo "No linting issues found."
          fi

